# Generated by Django 3.0.2 on 2020-01-17 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('color', models.CharField(choices=[('white', 'WE'), ('black', 'BK'), ('yellow', 'YW'), ('green', 'GN'), ('orange', 'OE'), ('grey', 'GY'), ('violet', 'VT'), ('magenta', 'MA')], max_length=16)),
                ('manufacturer', models.CharField(choices=[('Toyota', 'TY'), ('Mitsubishi', 'MI'), ('Mazda', 'MZ'), ('Nissan', 'NN'), ('Lexus', 'LS'), ('VAZ', 'LA'), ('Mercedes-Benz', 'MB'), ('BMW', 'BW'), ('Audi', 'AI')], max_length=16)),
                ('price', models.FloatField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1989), django.core.validators.MaxValueValidator(2020)])),
            ],
        ),
    ]
